version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: backend-fiscos
    ports:
      - "8080:8080"
      - "8080:8080"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - NFE_API_URL=http://nfe-api:3000
      - MONGO_URI=${MONGO_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE}
    env_file:
      - .env
    depends_on:
      - db
      - nfe-api

  db:
    image: postgres:15
    container_name: postgres-fiscos
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nfe-api:
    build:
      context: ./docker/nfe-api
      dockerfile: Dockerfile.prod
      args:
        GIT_BRANCH: ${NFE_API_BRANCH}
    container_name: nfe-api
    ports:
      - "3000:3000"
    env_file:
      - .env

volumes:
  postgres-data:
